version: '3'
services:
  express:
    image: expressjs:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=expressjs
    ports:
      - "8083:3001"
      - "8082:8082"
    volumes:
      - .:/usr/src/app
    container_name: express


  #vue:
  #  image: node:16
  #  working_dir: /usr/src/app
  #  command:
    #   - /bin/sh
    #   - -c
    #   - "npm install && npm run serve"
    # ports:
    #   - "8082:8082"
    # volumes:
    #   - .:/usr/src/app
    # - ./public:/usr/src/app/public
    #   - /usr/src/app/node_modules
    # container_name: vuejs
    # build:
    #   context: .
    #   dockerfile: Dockerfile
